global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'alert-receiver'

receivers:
  - name: 'alert-receiver'
    webhook_configs:
      - url: 'http://alert_receiver:9080/alerts'
        send_resolved: true
